### ISSUE TITLE
Docs are not building

### ISSUE THREAD

**Issue by mikemhenry** [OpenFreeEnergy/ofe-sphinx-theme#5]
```
Running Sphinx v6.2.1
making output directory... done

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/application.py", line 268, in __init__
    self._init_builder()
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/application.py", line 340, in _init_builder
    self.builder.init()
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 253, in init
    self.init_templates()
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/builders/html/__init__.py", line 304, in init_templates
    self.theme = theme_factory.create(themename)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/theming.py", line 230, in create
    return Theme(name, self.themes[name], factory=self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/theming.py", line 67, in __init__
    extract_zip(theme_path, self.themedir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/sphinx/theming.py", line 39, in extract_zip
    with ZipFile(filename) as archive:
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/zipfile.py", line 1253, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/ofe_sphinx_theme/theme/ofe_sphinx_theme'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/zipfile.py", line 1253, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/openfe/conda/910/lib/python3.10/site-packages/ofe_sphinx_theme/theme/ofe_sphinx_theme'
The full traceback has been saved in /tmp/sphinx-err-_shigaoh.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
```

**Comment by IAlibay** [comment]
:tada: thanks for fixing this!
